# Generated by Django 4.2.2 on 2023-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='prob_neg',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='prob_pos',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
