# Generated by Django 4.2.2 on 2023-07-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePred', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
